# Cholesky Decomposition

In [63]:
import numpy as np
import math

In [86]:
n=3
#A=5*np.random.rand(n,n)
A=np.array([[4,12,-16],[12,37,-43],[-16,-43,98]])
L=np.zeros([n,n])
A         

array([[  4,  12, -16],
       [ 12,  37, -43],
       [-16, -43,  98]])

In [87]:
def s1(L,i,j):
    su=0;
    print(L)
    for k in range(j):
        print(L[i,k])
        su=su+L[i,k]*L[j,k];
    return su   


In [88]:
#s1(L,4,3)

In [89]:
for i in range(n):
    for j in range(i+1):
        if i==j:
            L[i,j]=math.sqrt(A[i,j]-s1(L,i,j))
            #print(s1(L,i,j))
        else:
            L[i,j]=(A[i,j]-s1(L,i,j))/L[j,j]
                        
        

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2. 0. 0.]
 [6. 0. 0.]
 [0. 0. 0.]]
6.0
[[2. 0. 0.]
 [6. 1. 0.]
 [0. 0. 0.]]
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  0.  0.]]
-8.0
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  0.]]
-8.0
5.0


In [90]:
L

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])

In [36]:
import math

math.sqrt(4)

2.0